name = "swin_unet_sr_x4_v1"
seed = 42
epochs = 20

[hyper]
batch_size = 16
lr = 1e-3
train_val_test_split = [0.8, 0.1, 0.1]

[scheduler]
factor = 0.5
patience = 2

[data]
low_res_dir = "datasets/ffhq_lr_128"
high_res_dir = "datasets/ffhq_hr_512"
end_pos = 30000  # comment this line to load full data

[model]
swin_checkpoint = "microsoft/swinv2-base-patch4-window8-256"
img_mean = [0.485, 0.456, 0.406]
img_std = [0.229, 0.224, 0.225]
patch_size = 4
in_channels = 3
embed_dim = 60
skip_channels = [512, 256, 128]
decoder_channels = [1024, 512, 256, 128]
upscale = 4  # x4

[model.upsampler]
name = "LightweightUpsampler"
